App\Entity\SearchCity:
    properties:
        city:
            - NotBlank: ~
            - Length:
                min: 3
                max: 20
        street:
            - Length:
                min: 3
                max: 20
        postcode: 
            - Regex: '/^[0-9]{2}-[0-9]{3}$/'
            - App\Validator\RequiredIfStreetIsProvided: